version: '3'
services:
  redis:
    image: "redis:alpine"
    networks:
        default:
            aliases:
                - redis
    ports:
        - 6379
  web:
    build: ./
    ports:
        - 7778:7778
    entrypoint: ./docker-entrypoint.sh
    volumes:
        - .:/git-test
    depends_on:
      - redis
    environment:
      - PYTHONPATH=/git-test
