version: '3'
services:
  web:
    build: ./
    ports:
        - 7778:7778
    entrypoint: ./docker-entrypoint.sh
    volumes:
        - .:/fastapi-git-test
    environment:
      - PYTHONPATH=/fastapi-git-test
